### ISSUE TITLE
[Discussions] How to define cacheExtent to jump correct position? 

### ISSUE THREAD

**Issue by thaidmfinnick** [fluttercandies/flutter_scrollview_observer#83]
### Content

Hi again,
I use [flutter_scrollview_observer](https://github.com/fluttercandies/flutter_scrollview_observer) for rendering list messages, and my case is after I jump to specific message, I want to back to latest message, but when I use jumpTo(index: 0), it's wrong in some cases. 

Now, I set cache extent is very large: `9999999999`. But if I don't set cache extent, the jumping is not correct anymore.
I have followed [wiki](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/2%E3%80%81Scrolling-to-the-specified-index-location), but not clear about `reasonable` value you mention.

My snippet code below:

```
// load API when scroll to latest message
MessageChannelController.getMessageChannelUp(token, widget.selectedChannelId, selectedWorkspaceId, isNotifyListeners: true, limit: 30).then((v) {
   // when loaded
    final obItem = observerController.observeItem(index: 0);
    print('0: ${obItem?.scrollOffset} --- ${obItem?.displayPercentage}');
    observerController.jumpTo(index: 0);
    print(observerController.controller?.offset);
});
```

**Comment by LinXunFeng** [comment]
Can you provide a demo that reproduces the problem?

It is recommended to use the following code to back to latest message, so that there is no need to go through redundant calculations inside `scrollview_observer`.

https://github.com/fluttercandies/flutter_scrollview_observer/blob/ef7dfc546b1cd18e8d0e50df5daf89a0f52706b1/example/lib/features/scene/chat_demo/page/chat_page.dart#L229-L233

**Comment by thaidmfinnick** [comment]
Sorry for my late response. Using `animate to` works as expected. Thank you!
